version: '2'
services:
    debin1-app:
        image: debin1
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://debin1-postgresql:5432/debin1
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    debin1-postgresql:
        extends:
            file: postgresql.yml
            service: debin1-postgresql
